apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-nginx-demo
  namespace: thiru-argo-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argo-nginx-demo
  namespace: thiru-argo-demo
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx